/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Carousel: typeof import('./components/Carousel.vue')['default']
    Countdown: typeof import('./components/Countdown.vue')['default']
    CourseTable: typeof import('./components/CourseTable.vue')['default']
    DatePicker: typeof import('./components/DatePicker.vue')['default']
    Heisi: typeof import('./components/Heisi.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    User: typeof import('./components/User.vue')['default']
    WaterFall: typeof import('./components/Layout/WaterFall.vue')['default']
  }
}
